// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ScranHubDbContext))]
    [Migration("20260418180739_AmendCostAndRatingTables")]
    partial class AmendCostAndRatingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DAL.Entities.GroupCostOption", b =>
                {
                    b.Property<Guid>("GroupCostOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupCostOptionId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupCostOptions");

                    b.HasData(
                        new
                        {
                            GroupCostOptionId = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            Label = "Cheap"
                        },
                        new
                        {
                            GroupCostOptionId = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Label = "Reasonable"
                        },
                        new
                        {
                            GroupCostOptionId = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Label = "Pricey"
                        });
                });

            modelBuilder.Entity("DAL.Entities.GroupRatingOption", b =>
                {
                    b.Property<Guid>("GroupRatingOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupRatingOptionId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupRatingOptions");

                    b.HasData(
                        new
                        {
                            GroupRatingOptionId = new Guid("00000000-0000-0000-0002-000000000001"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            Label = "Great"
                        },
                        new
                        {
                            GroupRatingOptionId = new Guid("00000000-0000-0000-0002-000000000002"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Label = "Good"
                        },
                        new
                        {
                            GroupRatingOptionId = new Guid("00000000-0000-0000-0002-000000000003"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Label = "Average"
                        },
                        new
                        {
                            GroupRatingOptionId = new Guid("00000000-0000-0000-0002-000000000004"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Label = "Poor"
                        });
                });

            modelBuilder.Entity("DAL.Entities.GroupVenue", b =>
                {
                    b.Property<Guid>("GroupVenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FoodTypeId")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupCostOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupRatingOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VenueTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Visited")
                        .HasColumnType("bit");

                    b.HasKey("GroupVenueId");

                    b.HasIndex("GroupCostOptionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupRatingOptionId");

                    b.ToTable("GroupVenues");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AuthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Active = true,
                            Admin = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin User"
                        });
                });

            modelBuilder.Entity("DAL.Entities.UserFriend", b =>
                {
                    b.Property<Guid>("UserFriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserFriendId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFriends");
                });

            modelBuilder.Entity("DAL.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserGroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("DAL.Entities.GroupCostOption", b =>
                {
                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("GroupCostOptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DAL.Entities.GroupRatingOption", b =>
                {
                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("GroupRatingOptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DAL.Entities.GroupVenue", b =>
                {
                    b.HasOne("DAL.Entities.GroupCostOption", "GroupCostOption")
                        .WithMany()
                        .HasForeignKey("GroupCostOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("GroupVenues")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.GroupRatingOption", "GroupRatingOption")
                        .WithMany()
                        .HasForeignKey("GroupRatingOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("GroupCostOption");

                    b.Navigation("GroupRatingOption");
                });

            modelBuilder.Entity("DAL.Entities.UserFriend", b =>
                {
                    b.HasOne("DAL.Entities.User", "Friend")
                        .WithMany("ReceivedFriendships")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("InitiatedFriendships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.UserGroup", b =>
                {
                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Group", b =>
                {
                    b.Navigation("GroupCostOptions");

                    b.Navigation("GroupRatingOptions");

                    b.Navigation("GroupVenues");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("InitiatedFriendships");

                    b.Navigation("ReceivedFriendships");

                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
