// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ScranHubDbContext))]
    [Migration("20260421212939_AddRatingTables")]
    partial class AddRatingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.CostOption", b =>
                {
                    b.Property<Guid>("CostOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CostOptionId");

                    b.HasIndex("GroupId");

                    b.ToTable("CostOptions");

                    b.HasData(
                        new
                        {
                            CostOptionId = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Label = "Cheap"
                        },
                        new
                        {
                            CostOptionId = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Label = "Reasonable"
                        },
                        new
                        {
                            CostOptionId = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Label = "Pricey"
                        });
                });

            modelBuilder.Entity("DAL.Entities.CostUserRating", b =>
                {
                    b.Property<Guid>("CostUserRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CostOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupVenueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CostUserRatingId");

                    b.HasIndex("CostOptionId");

                    b.HasIndex("GroupVenueId");

                    b.HasIndex("UserId");

                    b.ToTable("CostUserRatings");
                });

            modelBuilder.Entity("DAL.Entities.FoodTypeOption", b =>
                {
                    b.Property<Guid>("FoodTypeOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("FoodTypeOptionId");

                    b.HasIndex("GroupId");

                    b.ToTable("FoodTypeOptions");

                    b.HasData(
                        new
                        {
                            FoodTypeOptionId = new Guid("00000000-0000-0000-0003-000000000001"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Label = "Café"
                        },
                        new
                        {
                            FoodTypeOptionId = new Guid("00000000-0000-0000-0003-000000000002"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Label = "Burgers"
                        },
                        new
                        {
                            FoodTypeOptionId = new Guid("00000000-0000-0000-0003-000000000003"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Label = "Chicken"
                        },
                        new
                        {
                            FoodTypeOptionId = new Guid("00000000-0000-0000-0003-000000000004"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            Label = "Pizza"
                        },
                        new
                        {
                            FoodTypeOptionId = new Guid("00000000-0000-0000-0003-000000000005"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            Label = "Oriental"
                        },
                        new
                        {
                            FoodTypeOptionId = new Guid("00000000-0000-0000-0003-000000000006"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            Label = "Other"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DAL.Entities.GroupVenue", b =>
                {
                    b.Property<Guid>("GroupVenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FoodTypeOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("VenueTypeOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Visited")
                        .HasColumnType("bit");

                    b.HasKey("GroupVenueId");

                    b.HasIndex("FoodTypeOptionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("VenueTypeOptionId");

                    b.ToTable("GroupVenues");
                });

            modelBuilder.Entity("DAL.Entities.RatingOption", b =>
                {
                    b.Property<Guid>("RatingOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("RatingOptionId");

                    b.HasIndex("GroupId");

                    b.ToTable("RatingOptions");

                    b.HasData(
                        new
                        {
                            RatingOptionId = new Guid("00000000-0000-0000-0002-000000000001"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Label = "Great"
                        },
                        new
                        {
                            RatingOptionId = new Guid("00000000-0000-0000-0002-000000000002"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Label = "Good"
                        },
                        new
                        {
                            RatingOptionId = new Guid("00000000-0000-0000-0002-000000000003"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Label = "Average"
                        },
                        new
                        {
                            RatingOptionId = new Guid("00000000-0000-0000-0002-000000000004"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            Label = "Poor"
                        });
                });

            modelBuilder.Entity("DAL.Entities.RatingUserRating", b =>
                {
                    b.Property<Guid>("RatingUserRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupVenueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RatingOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RatingUserRatingId");

                    b.HasIndex("GroupVenueId");

                    b.HasIndex("RatingOptionId");

                    b.HasIndex("UserId");

                    b.ToTable("RatingUserRatings");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AuthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Active = true,
                            Admin = true,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin User",
                            Email = "admin@example.com"
                        });
                });

            modelBuilder.Entity("DAL.Entities.UserFriend", b =>
                {
                    b.Property<Guid>("UserFriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FriendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserFriendId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFriends");
                });

            modelBuilder.Entity("DAL.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserGroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("DAL.Entities.VenueTypeOption", b =>
                {
                    b.Property<Guid>("VenueTypeOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("VenueTypeOptionId");

                    b.HasIndex("GroupId");

                    b.ToTable("VenueTypeOptions");

                    b.HasData(
                        new
                        {
                            VenueTypeOptionId = new Guid("00000000-0000-0000-0004-000000000001"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            Label = "Eat-In"
                        },
                        new
                        {
                            VenueTypeOptionId = new Guid("00000000-0000-0000-0004-000000000002"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            Label = "Takeaway"
                        },
                        new
                        {
                            VenueTypeOptionId = new Guid("00000000-0000-0000-0004-000000000003"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            Label = "Both"
                        });
                });

            modelBuilder.Entity("DAL.Entities.CostOption", b =>
                {
                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("CostOptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DAL.Entities.CostUserRating", b =>
                {
                    b.HasOne("DAL.Entities.CostOption", "CostOption")
                        .WithMany("CostUserRatings")
                        .HasForeignKey("CostOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.GroupVenue", "GroupVenue")
                        .WithMany("CostUserRatings")
                        .HasForeignKey("GroupVenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("CostUserRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostOption");

                    b.Navigation("GroupVenue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.FoodTypeOption", b =>
                {
                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("FoodTypeOptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DAL.Entities.GroupVenue", b =>
                {
                    b.HasOne("DAL.Entities.FoodTypeOption", "FoodTypeOption")
                        .WithMany("GroupVenues")
                        .HasForeignKey("FoodTypeOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("GroupVenues")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.VenueTypeOption", "VenueTypeOption")
                        .WithMany("GroupVenues")
                        .HasForeignKey("VenueTypeOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FoodTypeOption");

                    b.Navigation("Group");

                    b.Navigation("VenueTypeOption");
                });

            modelBuilder.Entity("DAL.Entities.RatingOption", b =>
                {
                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("RatingOptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DAL.Entities.RatingUserRating", b =>
                {
                    b.HasOne("DAL.Entities.GroupVenue", "GroupVenue")
                        .WithMany("RatingUserRatings")
                        .HasForeignKey("GroupVenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.RatingOption", "RatingOption")
                        .WithMany("RatingUserRatings")
                        .HasForeignKey("RatingOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("RatingUserRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupVenue");

                    b.Navigation("RatingOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.UserFriend", b =>
                {
                    b.HasOne("DAL.Entities.User", "Friend")
                        .WithMany("ReceivedFriendships")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("InitiatedFriendships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.UserGroup", b =>
                {
                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.VenueTypeOption", b =>
                {
                    b.HasOne("DAL.Entities.Group", "Group")
                        .WithMany("VenueTypeOptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DAL.Entities.CostOption", b =>
                {
                    b.Navigation("CostUserRatings");
                });

            modelBuilder.Entity("DAL.Entities.FoodTypeOption", b =>
                {
                    b.Navigation("GroupVenues");
                });

            modelBuilder.Entity("DAL.Entities.Group", b =>
                {
                    b.Navigation("CostOptions");

                    b.Navigation("FoodTypeOptions");

                    b.Navigation("GroupVenues");

                    b.Navigation("RatingOptions");

                    b.Navigation("UserGroups");

                    b.Navigation("VenueTypeOptions");
                });

            modelBuilder.Entity("DAL.Entities.GroupVenue", b =>
                {
                    b.Navigation("CostUserRatings");

                    b.Navigation("RatingUserRatings");
                });

            modelBuilder.Entity("DAL.Entities.RatingOption", b =>
                {
                    b.Navigation("RatingUserRatings");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("CostUserRatings");

                    b.Navigation("InitiatedFriendships");

                    b.Navigation("RatingUserRatings");

                    b.Navigation("ReceivedFriendships");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("DAL.Entities.VenueTypeOption", b =>
                {
                    b.Navigation("GroupVenues");
                });
#pragma warning restore 612, 618
        }
    }
}
