@WebApi_HostAddress = https://localhost:7079

### Get authentication token
POST {{WebApi_HostAddress}}/authentication/token
Content-Type: application/json
Accept: application/json

{
    "UserName": "test",
    "Password": "Password123!"
}