# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - app-scranhub-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Publish
        run: dotnet publish ./WebApi/WebApi.csproj -c Release --no-build -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Publish Functions
        run: dotnet publish ./Functions/Functions.csproj -c Release -o "${{env.DOTNET_ROOT}}/myfunctions"

      - name: Upload Functions artifact
        uses: actions/upload-artifact@v6
        with:
          name: .net-functions
          path: ${{env.DOTNET_ROOT}}/myfunctions
          include-hidden-files: true

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D360B6928404065B366574D57E71C2B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A87DB98DE6B4CFFB58CB5F754BEE3E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_443E238A1ECC43A7ABA3C70067E7DF61 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-scranhub-api'
          slot-name: 'Production'
          package: .

  deploy-functions:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Functions artifact
        uses: actions/download-artifact@v7
        with:
          name: .net-functions

      - name: List downloaded artifact contents
        run: Get-ChildItem -Force -Recurse | Select-Object FullName

      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D360B6928404065B366574D57E71C2B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A87DB98DE6B4CFFB58CB5F754BEE3E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_443E238A1ECC43A7ABA3C70067E7DF61 }}

      - name: Deploy to Azure Function App
        id: deploy-to-function
        uses: Azure/functions-action@v1
        with:
          app-name: 'scranhubfunctions'
          slot-name: 'Production'
          package: .

